// This file has been autogenerated from a class added in the UI designer.

using System;
using AmbiantLibrary;
using Foundation;
using WatchKit;

namespace Ambiance_watch.WatchOSApp
{
	public partial class MainInterfaceController : WKInterfaceController
	{
        bool enabled = false;

		public MainInterfaceController (IntPtr handle) : base (handle)
		{

		}

        public async override void Awake(NSObject context)
        {
            base.Awake(context);

            var ambiant = new AmbiantClient();
            var deviceData = await ambiant.GetDeviceDataAsync();

            OutsideTempLabel.SetText($"{deviceData[0]?.LastData.OutdoorTemp.ToString()}°");
            IndoorTempLabel.SetText($"{deviceData[0]?.LastData.IndoorTemp.ToString()}° Inside");

        }

        partial void MyButtonPressed()
        {
            enabled = !enabled;
            TheSwitch.SetOn(enabled);
        }

    }
}
